title: Open Data Day Panama
author: Floss Pa
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open data Panama project
twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed